### ISSUE TITLE
problem creating a targeted edge

### ISSUE THREAD

**Issue by sdrgabriel** [graphstream/gs-ui-android#12]
I have a problem that when creating the directed edge the elements disappear from the screen
This is the code I'm 
`public void applyAddAresta(String noFrom, String noTo, String peso) {`
`String nomeAresta = noFrom + noTo;`
        `String nomeArestaInvertido = noTo + noFrom;`
       ` int tam = graph.getEdgeCount();`
        `boolean arestaExiste = false;`
       ` // Se tam == 0 não tem aresta então cria uma direto.`
       ` if (tam == 0){`
            `if (peso.equals("")){`
               ` peso = "1";`
                `graph.addEdge(nomeAresta, noFrom, noTo, true)`
                       ` .setAttribute("length", peso);`
                `listArestas.add(nomeAresta);`
                `listPeso.add(peso);`
          `  } else {`
             `   graph.addEdge(nomeAresta, noFrom, noTo, true)`
                    `    .setAttribute("length", peso);`
              `  graph.getEdge(nomeAresta).setAttribute("ui.label", peso);`
               ` listArestas.add(nomeAresta);`
               ` listPeso.add(peso);`
         `   }`
      `  }`
      `  // Se tam != 0 então já tem aresta, tem que olhar uma a uma antes de add uma nova.`
      `  if (tam != 0){`
            `for (int i = 0; i < tam; i++) {`
             `   String compara = graph.getEdge(i).getId();`
              `  if (compara.equals(nomeAresta) || compara.equals(nomeArestaInvertido)) {`
              `      arestaExiste = true;`
            `    }`
         `   }`
     `   }`
       ` // Se arestaExiste == true a aresta já existe caso contrario cria a aresta.`
      `  if (arestaExiste){`
         `   chamaToast(getString(R.string.aresta_existente));`
  `      } else if (tam >= 1){`
           ` if (peso.equals("")){`
             `   peso = "1";`
              `  graph.addEdge(nomeAresta, noFrom, noTo, true)`
                 `       .setAttribute("length", peso);`
             `   listArestas.add(nomeAresta);`
              `  listPeso.add(peso);`
        `    } else {`
                `graph.addEdge(nomeAresta, noFrom, noTo, true)`
                   `     .setAttribute("length", peso);`
              `  graph.getEdge(nomeAresta).setAttribute("ui.label", peso);`
             ` `  listArestas.add(nomeAresta);`
               ` listPeso.add(peso);`
          `  }`
       ` }`
`}`

I have this image of the problem, if one uses the same code without being directed not the problem, but I want to create the two types of graphs.

![image](https://user-images.githubusercontent.com/48629754/56516740-ae9ec180-6511-11e9-88e9-6049c0e696d2.png)

I'm doing the wrong code, someone can help me.

**Comment by hichbra** [comment]
I can't answer with that, can you provide a [minimal example](http://sscce.org/) of your problem ?

**Comment by sdrgabriel** [comment]
well-simplified, assuming it already has nodes A and B if I use this code and create a non-directed edge works well: 
`graph.addEdge("AB", "A", "B", false);`
![image](https://user-images.githubusercontent.com/48629754/56583059-11926600-65af-11e9-9af3-22d3cedb7738.png)
but if I use this code to create the directed edge the graph gets all weird:
`graph.addEdge("AB", "A", "B", true);`
![image](https://user-images.githubusercontent.com/48629754/56583254-882f6380-65af-11e9-93bf-7ea287040728.png)
the edge is down here and the nodes go up into the beyond.
I do not know what's happening, I was using this link https://github.com/graphstream/gs-ui-android-test

**Comment by hichbra** [comment]
I understand your problem, I'm asking you to provide a functionnal code example. You say you had this problem using gs-ui-android-test, but everything works fine with me.

What example did you use ?

**Comment by sdrgabriel** [comment]
I made an example of my problem below, I put the java and the activity.
[Exem.zip](https://github.com/graphstream/gs-ui-android/files/3108274/Exem.zip)

**Comment by hichbra** [comment]
I can't reproduce this issue, your example works fine : 
![issue](https://user-images.githubusercontent.com/10866042/56647264-7ae2a980-6681-11e9-854b-58212ce1563e.png)

Which smartphone do you use and what is your real css (assuming it was not the one in your example).
Also, which versions do you use of gs-core and gs-ui-android ?

**Comment by sdrgabriel** [comment]
Thanks for the help, I ended up realizing that the error only happens in the Nox emulator when I tested it on my cell phone, it had no problem thanks for the help.
