### ISSUE TITLE
DFS and BFS algorithm?

### ISSUE THREAD

**Issue by sdrgabriel** [graphstream/gs-ui-android#14]
I looked in gs-algo but did not find anything of the algorithms dfs and bfs, are they available?
if not how I can implement them.

**Comment by pigne** [comment]
Yes they are.

From the [documentation](http://graphstream-project.org/doc/Tutorials/Storing-retrieving-and-displaying-data-in-graphs/#an-example-using-attributes-and-the-viewer) :

> The `Node` class provides iterators on its set of neighbors (both directed only or undirected), as well as two iterators to explore the graph starting from this node in depth-first or breadth-first order.

```java
    public void explore(Node source) {
        Iterator<? extends Node> k = source.getBreadthFirstIterator();

        while (k.hasNext()) {
            Node next = k.next();
            next.setAttribute("ui.class", "marked");
            sleep();   
        }
    }
```

Also, check the [API](https://data.graphstream-project.org/api/gs-core/current/org/graphstream/graph/Node.html#getBreadthFirstIterator()).
