### ISSUE TITLE
Can't zoom using using the android Default Fragemnt.

### ISSUE THREAD

**Issue by TobiasIsak** [graphstream/gs-ui-android#15]
When fetching the viewer from the default fragment, it lacks necessary methods to be able to zoom.

**Comment by hichbra** [comment]
You have access to the camera object in the onStart method with the fragment 
```fragment.getViewer().getDefaultView().getCamera()```
Use setViewPercent to zoom. Also, you can still combine these methods with the [CSS properties](http://graphstream-project.org/doc/Advanced-Concepts/GraphStream-CSS-Reference/).

**Comment by TobiasIsak** [comment]
oh, thank you for the help!
