### ISSUE TITLE
Full screen flash when finishing activity with graph fragment in it

### ISSUE THREAD

**Issue by TobiasIsak** [graphstream/gs-ui-android#18]
So what I'm currently doing when closing the activity that handles the DefaultFragment is this:

privateFragment.getFragmentManager().popBackStack();
finish();

When the activity switches to the other a white screen show across the whole phone and then it finally switches over to the parent activity.
if I do not use popBackStack on the DefaultFragment, the activitys parent I'm going to crashes.
Is the fragments onDestroy() or onPause() doing something unusual with the rendering?

**Comment by hichbra** [comment]
As you can see in [DefaultFragment class](https://github.com/graphstream/gs-ui-android/blob/2.0-alpha/app/src/main/java/org/graphstream/ui/android_viewer/util/DefaultFragment.java), no processing is perform in onDestroy() or onPause(). That means after onPause() if the fragment is reload, a new view is created and added, and if it's done after onDestroy(), the Viewer/Renderer will reset.
