### ISSUE TITLE
 error between the distance of the nodes

### ISSUE THREAD

**Issue by paulagaitan97** [graphstream/gs-ui-android#20]
I would like to know how to solve this error. 👍 

![error](https://user-images.githubusercontent.com/23261158/77862240-c41b7180-71df-11ea-8b19-ee452174fc52.jpeg)

**Comment by hichbra** [comment]
Hi !

I've never seen this issue before. Did you try to run the [tests](https://github.com/graphstream/gs-ui-android-test) ?

**Comment by paulagaitan97** [comment]
yes. what happens is that you set the auto layout to true. I want it to be more separated so that the text is read.  another question .. how to activate the zoom.?

**Comment by hichbra** [comment]
Ok I understand now, it's not an issue. You need to correctly custom your CSS properties to match your data. Example : 
```css
node { 
    text-size: 48; 
    text-alignment: left;
    fill-color: white; 
    size: 1000px, 100px; 
    padding: 150px, 0px;
    shape: box; 
}
```
You should avoid using very long labels. It's up to you to find the best parameter for your needs, you can use the [tests](https://github.com/graphstream/gs-ui-android-test/blob/master/app/src/main/java/ui/graphstream/org/gs_ui_androidtestFull/Activity_TestShapeDecor.java) and the [documentation](http://graphstream-project.org/doc/Advanced-Concepts/GraphStream-CSS-Reference/) to help you.

Also, the zoom doesn't need to be activated, you can do it by code : 
```java
fragment.getViewer().getDefaultView().getCamera().setViewPercent(0.5);
```
 and from the next version you will able to do it by touch. If you need this feature now, you can use the dev branch of gs-ui-android 
```gradle
api 'com.github.graphstream:gs-ui-android:dev-SNAPSHOT'
```

**Comment by paulagaitan97** [comment]
another question . the graphic can be applied in a fragment. I use navigation drawer.

**Comment by paulagaitan97** [comment]
if i change the api version. I have an error in the default fragment. Is not recognized

**Comment by hichbra** [comment]
As the [README](https://github.com/graphstream/gs-ui-android/tree/dev) file said in the dev branch, you need now to use getSupportFragmentManager(), because [DefaultFragment](https://github.com/graphstream/gs-ui-android/blob/dev/app/src/main/java/org/graphstream/ui/android_viewer/util/DefaultFragment.java) get updated to the v4 version.
