### ISSUE TITLE
graphics incompatible with fragments

### ISSUE THREAD

**Issue by Nel-dev** [graphstream/gs-ui-android#21]
How can I implement the graph of your implementation in a fragment?

**Comment by hichbra** [comment]
Use the DefaultFragment class. There are currently 2 versions, [the first and current one](https://github.com/graphstream/gs-ui-android/blob/2.0-alpha/app/src/main/java/org/graphstream/ui/android_viewer/util/DefaultFragment.java) implement 
[Fragment](https://developer.android.com/reference/android/app/Fragment) witch is deprecated from API level 28. 
Then you can find the [second and future version](https://github.com/graphstream/gs-ui-android/blob/dev/app/src/main/java/org/graphstream/ui/android_viewer/util/DefaultFragment.java) in the dev branch, witch implement [v4.app.Fragment](https://developer.android.com/reference/android/support/v4/app/Fragment.html).

 You can find many examples [here](https://github.com/graphstream/gs-ui-android-test/tree/master/app/src/main/java/ui/graphstream/org/gs_ui_androidtestFull). You can find the sames examples but with the last version [here](https://github.com/hichbra/gs-ui-android-test/tree/newFragment/app/src/main/java/ui/graphstream/org/gs_ui_androidtestFull).

Good luck.

**Comment by Nel-dev** [comment]
in the examples there is not one implemented with a fragment. everyone is with activities.

**Comment by hichbra** [comment]
DefaultFragment is a fragment himself, take a look at the class.

**Comment by Nel-dev** [comment]
![image](https://user-images.githubusercontent.com/26652429/78948502-34eb4500-7a8e-11ea-819d-511b0af10890.png)

inconvertible types. cannot cast android.app.Fragment to model.DefaultFragment

**Comment by Nel-dev** [comment]
![image](https://user-images.githubusercontent.com/26652429/78949477-471ab280-7a91-11ea-8073-84a135bbedf2.png)


what can that error be?
