### ISSUE TITLE
Error setting a node image

### ISSUE THREAD

**Issue by buddel99** [graphstream/gs-ui-android#22]
When I use the StyleSheet below without the bold part everything works fine, but if I try to add the image as a node image it throws the Error below the the StyleSheet. I tried using the same image as a text icon and that work fine, only using it as an image for the node throws an error. 
I hope you can help me determine if its my fault or if there is a bug in the library.

```
String graphStyleSheet = ""
            + "graph {"
            + "	canvas-color: white;  "
            + "	fill-mode: gradient-radial; "
            + "	fill-color: white, #EEEEEE; "
            + "	padding: 60px; "
            + "}"
            + ""
            + "node {"
            **+ " fill-mode: image-scaled-ratio-max;"
            + " fill-image: url('" + R.drawable.gslogo + "');"**
            + " size: 65px;"
            + "} "
            + ""
            + "node:clicked { "
            + "	stroke-mode: plain;"
            + "	stroke-color: #007eC0;"
            + "}"
            + ""
            + "edge { 	shape: line; size: 5px; 	fill-mode: plain; 	arrow-shape: arrow; arrow-size: 20px, 15px; } ";

```
### Error Message: 
> 2020-11-10 10:39:43.367 2537-2537/me.testapp E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: me.testapp, PID: 2537
>     java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
>         at org.graphstream.ui.android.util.Background.getResizedBitmap(Background.java:37)
>         at org.graphstream.ui.android.util.Background.<init>(Background.java:32)
>         at org.graphstream.ui.android.renderer.shape.android.ShapePaint$ShapeImageScaledRatioMaxPaint.paint(ShapePaint.java:417)
>         at org.graphstream.ui.android.renderer.shape.android.ShapePaint$ShapeAreaPaint.paint(ShapePaint.java:229)
>         at org.graphstream.ui.android.renderer.shape.android.shapePart.Fillable.fill(Fillable.java:44)
>         at org.graphstream.ui.android.renderer.shape.android.shapePart.Fillable.fill(Fillable.java:64)
>         at org.graphstream.ui.android.renderer.shape.android.baseShapes.RectangularAreaShape.render(RectangularAreaShape.java:32)
>         at org.graphstream.ui.android.renderer.NodeRenderer.renderElement(NodeRenderer.java:40)
>         at org.graphstream.ui.android.renderer.StyleRenderer.lambda$new$3$StyleRenderer(StyleRenderer.java:139)
>         at org.graphstream.ui.android.renderer.-$$Lambda$StyleRenderer$2-aDDhVkWUPF4d9dhHS3RMNTrx8.apply(Unknown Source:8)
>         at org.graphstream.ui.android.renderer.StyleRenderer.lambda$render$0$StyleRenderer(StyleRenderer.java:65)
>         at org.graphstream.ui.android.renderer.-$$Lambda$StyleRenderer$ng2Vbx8VkPaLuFXZ08-rCwCztI4.accept(Unknown Source:10)
>         at java.lang.Iterable.forEach(Iterable.java:75)
>         at org.graphstream.ui.android.renderer.StyleRenderer.render(StyleRenderer.java:61)
>         at org.graphstream.ui.android.renderer.StyleRenderer.render(StyleRenderer.java:37)
>         at org.graphstream.ui.android.AndroidFullGraphRenderer.lambda$null$4$AndroidFullGraphRenderer(AndroidFullGraphRenderer.java:243)
>         at org.graphstream.ui.android.-$$Lambda$AndroidFullGraphRenderer$M4eXji0LgTlGtTY1hBTDU7Lvg10.accept(Unknown Source:4)
>         at java.lang.Iterable.forEach(Iterable.java:75)
>         at org.graphstream.ui.android.AndroidFullGraphRenderer.lambda$render$5$AndroidFullGraphRenderer(AndroidFullGraphRenderer.java:241)
>         at org.graphstream.ui.android.-$$Lambda$AndroidFullGraphRenderer$jk9cHC21XryH714NOLAQCknFJ9k.accept(Unknown Source:4)
>         at java.lang.Iterable.forEach(Iterable.java:75)
>         at org.graphstream.ui.android.AndroidFullGraphRenderer.render(AndroidFullGraphRenderer.java:240)
>         at org.graphstream.ui.android.AndroidFullGraphRenderer.render(AndroidFullGraphRenderer.java:92)
>         at org.graphstream.ui.android_viewer.DefaultView.render(DefaultView.java:104)
>         at org.graphstream.ui.android_viewer.DefaultView.onDraw(DefaultView.java:120)
>         at android.view.View.draw(View.java:19237)
>         at android.view.SurfaceView.draw(SurfaceView.java:383)
>         at android.view.View.updateDisplayListIfDirty(View.java:18187)
>         at android.view.View.draw(View.java:18965)
>         at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
>         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
>         at android.view.View.updateDisplayListIfDirty(View.java:18178)
>         at android.view.View.draw(View.java:18965)
>         at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
>         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
>         at android.view.View.updateDisplayListIfDirty(View.java:18178)
>         at android.view.View.draw(View.java:18965)
>         at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
>         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
>         at android.view.View.updateDisplayListIfDirty(View.java:18178)
>         at android.view.View.draw(View.java:18965)
>         at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
>         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
>         at android.view.View.updateDisplayListIfDirty(View.java:18178)
>         at android.view.View.draw(View.java:18965)
>         at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
>         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
>         at android.view.View.updateDisplayListIfDirty(View.java:18178)
>         at android.view.View.draw(View.java:18965)
>         at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
> 2020-11-10 10:39:43.370 2537-2537/me.testapp E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
>         at android.view.View.updateDisplayListIfDirty(View.java:18178)
>         at android.view.View.draw(View.java:18965)
>         at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
>         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
>         at android.view.View.draw(View.java:19240)
>         at com.android.internal.policy.DecorView.draw(DecorView.java:788)
>         at android.view.View.updateDisplayListIfDirty(View.java:18187)
>         at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:676)
>         at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:682)
>         at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:790)
>         at android.view.ViewRootImpl.draw(ViewRootImpl.java:3006)
>         at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2810)
>         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2363)
>         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1396)
>         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6778)
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:778)
>         at android.view.Choreographer.doFrame(Choreographer.java:713)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
>         at android.os.Handler.handleCallback(Handler.java:790)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6521)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by buddel99** [comment]
I found out that in Background.java in getResizedBitmap (line 36 to 50) the Bitmap.createBitmap checks if the passed x or y are bigger than 0 but the method always gets 0 passed because it's hardcoded in there.
```
public static Bitmap getResizedBitmap(Bitmap bm, int newWidth, int newHeight) {
        int width = bm.getWidth();
        int height = bm.getHeight();
        float scaleWidth = ((float) newWidth) / width;
        float scaleHeight = ((float) newHeight) / height;

        Matrix matrix = new Matrix();
        // Resize the bitmap
        matrix.postScale(scaleWidth, scaleHeight);

        Bitmap resizedBitmap = Bitmap.createBitmap(
                bm, 0, 0, width, height, matrix, false);
        bm.recycle();
        return resizedBitmap;
    }
```

This results in an error thrown by checkXYSign which gets called as the first method by createBitmap in Bitmap.java
  ```
 private static void checkXYSign(int x, int y) {
        if (x < 0) {
            throw new IllegalArgumentException("x must be >= 0");
        }
        if (y < 0) {
            throw new IllegalArgumentException("y must be >= 0");
        }
    }

```

**Comment by hichbra** [comment]
I don't see any problem here, the if statement is ```if (x < 0)```, so if ```x = 0``` he should pass.

You can find a working example of a node image [here](https://github.com/graphstream/gs-ui-android-test/blob/master/app/src/main/java/ui/graphstream/org/gs_ui_androidtestFull/Activity_TestShapeDecor.java) or [here](https://github.com/graphstream/gs-ui-android-test/blob/master/app/src/main/java/ui/graphstream/org/gs_ui_androidtestFull/Activity_TestIcons.java) for a dynamic icon change.

**Comment by buddel99** [comment]
First of all thanks for the quick response, yes you are right and I was kind of stupid 😅.
The examples work fine but is it possible to show an image as the filling of e.g. a round node?
