### ISSUE TITLE
problem with touching the graph field

### ISSUE THREAD

**Issue by sdrgabriel** [graphstream/gs-ui-android#7]
I wanted to implement one that when touching the screen create a node, but I'm having difficulty because when I tap the screen does nothing else and when I tap the bottom menu it works the touch.

![Screenshot_20190322-203513_Athena_tg 1](https://user-images.githubusercontent.com/48629754/54859072-e5ea3a80-4ce7-11e9-91f4-617f58c884be.jpg)

**Comment by hichbra** [comment]
You must implements ViewerListener. You can find some example [here](https://github.com/graphstream/gs-ui-android-test/tree/master/app/src/main/java/ui/graphstream/org/gs_ui_androidtestFull) to help you.

**Comment by sdrgabriel** [comment]
thanks, i will read this, could u tell me what is this blue box? and can I disable this?

**Comment by hichbra** [comment]
It's likely the selection box, it should appear when you slide your finger on the screen. You should try some of the tests I gave you.

**Comment by sdrgabriel** [comment]
im trying to use viwerpipe but it is returning null, does it have any difference in making the viewer in a fragment?
