### ISSUE TITLE
how can I use Dijkstra's Shortest Path?

### ISSUE THREAD

**Issue by sdrgabriel** [graphstream/gs-ui-android#9]
I would like to know how to use the algorithms of gs-algo in android, I saw some examples on the site but I could not make it work on android, could you give me an example of its use

**Comment by hichbra** [comment]
There no specificity to gs-ui-android, you can use it in a [normal way](https://github.com/graphstream/gs-algo/blob/release/2.0-alpha/src-test/org/graphstream/algorithm/test/TestDijkstra.java). Make sure your dependencies are correct.

```gradle
dependencies {
   ...
   api 'com.github.graphstream:gs-algo:2.0-alpha'
}
```
